// Code generated by MockGen. DO NOT EDIT.
// Source: i_hunt_board_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_hunt_board_repository.go -destination=mocks/mock_i_hunt_board_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIHuntBoardRepository is a mock of IHuntBoardRepository interface.
type MockIHuntBoardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIHuntBoardRepositoryMockRecorder
	isgomock struct{}
}

// MockIHuntBoardRepositoryMockRecorder is the mock recorder for MockIHuntBoardRepository.
type MockIHuntBoardRepositoryMockRecorder struct {
	mock *MockIHuntBoardRepository
}

// NewMockIHuntBoardRepository creates a new mock instance.
func NewMockIHuntBoardRepository(ctrl *gomock.Controller) *MockIHuntBoardRepository {
	mock := &MockIHuntBoardRepository{ctrl: ctrl}
	mock.recorder = &MockIHuntBoardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHuntBoardRepository) EXPECT() *MockIHuntBoardRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockIHuntBoardRepository) FindAll(executionContext context.Context) ([]entities.HuntBoardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", executionContext)
	ret0, _ := ret[0].([]entities.HuntBoardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIHuntBoardRepositoryMockRecorder) FindAll(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIHuntBoardRepository)(nil).FindAll), executionContext)
}

// Rewrite mocks base method.
func (m *MockIHuntBoardRepository) Rewrite(executionContext context.Context, huntBoardEntries []entities.HuntBoardEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rewrite", executionContext, huntBoardEntries)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rewrite indicates an expected call of Rewrite.
func (mr *MockIHuntBoardRepositoryMockRecorder) Rewrite(executionContext, huntBoardEntries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rewrite", reflect.TypeOf((*MockIHuntBoardRepository)(nil).Rewrite), executionContext, huntBoardEntries)
}
