// Code generated by MockGen. DO NOT EDIT.
// Source: i_hunt_pipeline_application.go
//
// Generated by this command:
//
//	mockgen -source=i_hunt_pipeline_application.go -destination=mocks/mock_i_hunt_pipeline_application.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/dto"
	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIHuntPipelineApplication is a mock of IHuntPipelineApplication interface.
type MockIHuntPipelineApplication struct {
	ctrl     *gomock.Controller
	recorder *MockIHuntPipelineApplicationMockRecorder
	isgomock struct{}
}

// MockIHuntPipelineApplicationMockRecorder is the mock recorder for MockIHuntPipelineApplication.
type MockIHuntPipelineApplicationMockRecorder struct {
	mock *MockIHuntPipelineApplication
}

// NewMockIHuntPipelineApplication creates a new mock instance.
func NewMockIHuntPipelineApplication(ctrl *gomock.Controller) *MockIHuntPipelineApplication {
	mock := &MockIHuntPipelineApplication{ctrl: ctrl}
	mock.recorder = &MockIHuntPipelineApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHuntPipelineApplication) EXPECT() *MockIHuntPipelineApplicationMockRecorder {
	return m.recorder
}

// RunHuntRound mocks base method.
func (m *MockIHuntPipelineApplication) RunHuntRound(executionContext context.Context, stopBetweenSteps <-chan struct{}, triggerSource vo.PipelineRunTriggerSourceVo) dto.HuntRoundDto {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunHuntRound", executionContext, stopBetweenSteps, triggerSource)
	ret0, _ := ret[0].(dto.HuntRoundDto)
	return ret0
}

// RunHuntRound indicates an expected call of RunHuntRound.
func (mr *MockIHuntPipelineApplicationMockRecorder) RunHuntRound(executionContext, stopBetweenSteps, triggerSource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunHuntRound", reflect.TypeOf((*MockIHuntPipelineApplication)(nil).RunHuntRound), executionContext, stopBetweenSteps, triggerSource)
}
