// Code generated by MockGen. DO NOT EDIT.
// Source: i_coin_intelligence_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_coin_intelligence_repository.go -destination=mocks/mock_i_coin_intelligence_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockICoinIntelligenceRepository is a mock of ICoinIntelligenceRepository interface.
type MockICoinIntelligenceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICoinIntelligenceRepositoryMockRecorder
	isgomock struct{}
}

// MockICoinIntelligenceRepositoryMockRecorder is the mock recorder for MockICoinIntelligenceRepository.
type MockICoinIntelligenceRepositoryMockRecorder struct {
	mock *MockICoinIntelligenceRepository
}

// NewMockICoinIntelligenceRepository creates a new mock instance.
func NewMockICoinIntelligenceRepository(ctrl *gomock.Controller) *MockICoinIntelligenceRepository {
	mock := &MockICoinIntelligenceRepository{ctrl: ctrl}
	mock.recorder = &MockICoinIntelligenceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoinIntelligenceRepository) EXPECT() *MockICoinIntelligenceRepositoryMockRecorder {
	return m.recorder
}

// FindByPipelineRunID mocks base method.
func (m *MockICoinIntelligenceRepository) FindByPipelineRunID(executionContext context.Context, pipelineRunID uint) ([]entities.CoinIntelligence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPipelineRunID", executionContext, pipelineRunID)
	ret0, _ := ret[0].([]entities.CoinIntelligence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPipelineRunID indicates an expected call of FindByPipelineRunID.
func (mr *MockICoinIntelligenceRepositoryMockRecorder) FindByPipelineRunID(executionContext, pipelineRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPipelineRunID", reflect.TypeOf((*MockICoinIntelligenceRepository)(nil).FindByPipelineRunID), executionContext, pipelineRunID)
}

// FindPublishedSince mocks base method.
func (m *MockICoinIntelligenceRepository) FindPublishedSince(executionContext context.Context, publishedSince time.Time) ([]entities.CoinIntelligence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPublishedSince", executionContext, publishedSince)
	ret0, _ := ret[0].([]entities.CoinIntelligence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPublishedSince indicates an expected call of FindPublishedSince.
func (mr *MockICoinIntelligenceRepositoryMockRecorder) FindPublishedSince(executionContext, publishedSince any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPublishedSince", reflect.TypeOf((*MockICoinIntelligenceRepository)(nil).FindPublishedSince), executionContext, publishedSince)
}

// SaveNew mocks base method.
func (m *MockICoinIntelligenceRepository) SaveNew(executionContext context.Context, coinIntelligences []entities.CoinIntelligence) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNew", executionContext, coinIntelligences)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNew indicates an expected call of SaveNew.
func (mr *MockICoinIntelligenceRepositoryMockRecorder) SaveNew(executionContext, coinIntelligences any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNew", reflect.TypeOf((*MockICoinIntelligenceRepository)(nil).SaveNew), executionContext, coinIntelligences)
}
