// Code generated by MockGen. DO NOT EDIT.
// Source: i_coin_verdict_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_coin_verdict_repository.go -destination=mocks/mock_i_coin_verdict_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockICoinVerdictRepository is a mock of ICoinVerdictRepository interface.
type MockICoinVerdictRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICoinVerdictRepositoryMockRecorder
	isgomock struct{}
}

// MockICoinVerdictRepositoryMockRecorder is the mock recorder for MockICoinVerdictRepository.
type MockICoinVerdictRepositoryMockRecorder struct {
	mock *MockICoinVerdictRepository
}

// NewMockICoinVerdictRepository creates a new mock instance.
func NewMockICoinVerdictRepository(ctrl *gomock.Controller) *MockICoinVerdictRepository {
	mock := &MockICoinVerdictRepository{ctrl: ctrl}
	mock.recorder = &MockICoinVerdictRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoinVerdictRepository) EXPECT() *MockICoinVerdictRepositoryMockRecorder {
	return m.recorder
}

// CreateAll mocks base method.
func (m *MockICoinVerdictRepository) CreateAll(executionContext context.Context, coinVerdicts []entities.CoinVerdict) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAll", executionContext, coinVerdicts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAll indicates an expected call of CreateAll.
func (mr *MockICoinVerdictRepositoryMockRecorder) CreateAll(executionContext, coinVerdicts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAll", reflect.TypeOf((*MockICoinVerdictRepository)(nil).CreateAll), executionContext, coinVerdicts)
}

// FindByPipelineRunID mocks base method.
func (m *MockICoinVerdictRepository) FindByPipelineRunID(executionContext context.Context, pipelineRunID uint) ([]entities.CoinVerdict, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPipelineRunID", executionContext, pipelineRunID)
	ret0, _ := ret[0].([]entities.CoinVerdict)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPipelineRunID indicates an expected call of FindByPipelineRunID.
func (mr *MockICoinVerdictRepositoryMockRecorder) FindByPipelineRunID(executionContext, pipelineRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPipelineRunID", reflect.TypeOf((*MockICoinVerdictRepository)(nil).FindByPipelineRunID), executionContext, pipelineRunID)
}
