// Code generated by MockGen. DO NOT EDIT.
// Source: i_coin_candidate_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_coin_candidate_repository.go -destination=mocks/mock_i_coin_candidate_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockICoinCandidateRepository is a mock of ICoinCandidateRepository interface.
type MockICoinCandidateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICoinCandidateRepositoryMockRecorder
	isgomock struct{}
}

// MockICoinCandidateRepositoryMockRecorder is the mock recorder for MockICoinCandidateRepository.
type MockICoinCandidateRepositoryMockRecorder struct {
	mock *MockICoinCandidateRepository
}

// NewMockICoinCandidateRepository creates a new mock instance.
func NewMockICoinCandidateRepository(ctrl *gomock.Controller) *MockICoinCandidateRepository {
	mock := &MockICoinCandidateRepository{ctrl: ctrl}
	mock.recorder = &MockICoinCandidateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoinCandidateRepository) EXPECT() *MockICoinCandidateRepositoryMockRecorder {
	return m.recorder
}

// CreateAll mocks base method.
func (m *MockICoinCandidateRepository) CreateAll(executionContext context.Context, coinCandidates []entities.CoinCandidate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAll", executionContext, coinCandidates)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAll indicates an expected call of CreateAll.
func (mr *MockICoinCandidateRepositoryMockRecorder) CreateAll(executionContext, coinCandidates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAll", reflect.TypeOf((*MockICoinCandidateRepository)(nil).CreateAll), executionContext, coinCandidates)
}

// FindByPipelineRunID mocks base method.
func (m *MockICoinCandidateRepository) FindByPipelineRunID(executionContext context.Context, pipelineRunID uint) ([]entities.CoinCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPipelineRunID", executionContext, pipelineRunID)
	ret0, _ := ret[0].([]entities.CoinCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPipelineRunID indicates an expected call of FindByPipelineRunID.
func (mr *MockICoinCandidateRepositoryMockRecorder) FindByPipelineRunID(executionContext, pipelineRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPipelineRunID", reflect.TypeOf((*MockICoinCandidateRepository)(nil).FindByPipelineRunID), executionContext, pipelineRunID)
}
