// Code generated by MockGen. DO NOT EDIT.
// Source: i_hunt_verdict_strategist_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_hunt_verdict_strategist_proxy.go -destination=mocks/mock_i_hunt_verdict_strategist_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIHuntVerdictStrategistProxy is a mock of IHuntVerdictStrategistProxy interface.
type MockIHuntVerdictStrategistProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIHuntVerdictStrategistProxyMockRecorder
	isgomock struct{}
}

// MockIHuntVerdictStrategistProxyMockRecorder is the mock recorder for MockIHuntVerdictStrategistProxy.
type MockIHuntVerdictStrategistProxyMockRecorder struct {
	mock *MockIHuntVerdictStrategistProxy
}

// NewMockIHuntVerdictStrategistProxy creates a new mock instance.
func NewMockIHuntVerdictStrategistProxy(ctrl *gomock.Controller) *MockIHuntVerdictStrategistProxy {
	mock := &MockIHuntVerdictStrategistProxy{ctrl: ctrl}
	mock.recorder = &MockIHuntVerdictStrategistProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHuntVerdictStrategistProxy) EXPECT() *MockIHuntVerdictStrategistProxyMockRecorder {
	return m.recorder
}

// SynthesizeVerdicts mocks base method.
func (m *MockIHuntVerdictStrategistProxy) SynthesizeVerdicts(executionContext context.Context, materials []vo.HuntVerdictMaterialVo) ([]vo.HuntVerdictAnswerVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SynthesizeVerdicts", executionContext, materials)
	ret0, _ := ret[0].([]vo.HuntVerdictAnswerVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SynthesizeVerdicts indicates an expected call of SynthesizeVerdicts.
func (mr *MockIHuntVerdictStrategistProxyMockRecorder) SynthesizeVerdicts(executionContext, materials any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SynthesizeVerdicts", reflect.TypeOf((*MockIHuntVerdictStrategistProxy)(nil).SynthesizeVerdicts), executionContext, materials)
}
