// Code generated by MockGen. DO NOT EDIT.
// Source: i_perpetual_market_structure_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_perpetual_market_structure_proxy.go -destination=mocks/mock_i_perpetual_market_structure_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIPerpetualMarketStructureProxy is a mock of IPerpetualMarketStructureProxy interface.
type MockIPerpetualMarketStructureProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIPerpetualMarketStructureProxyMockRecorder
	isgomock struct{}
}

// MockIPerpetualMarketStructureProxyMockRecorder is the mock recorder for MockIPerpetualMarketStructureProxy.
type MockIPerpetualMarketStructureProxyMockRecorder struct {
	mock *MockIPerpetualMarketStructureProxy
}

// NewMockIPerpetualMarketStructureProxy creates a new mock instance.
func NewMockIPerpetualMarketStructureProxy(ctrl *gomock.Controller) *MockIPerpetualMarketStructureProxy {
	mock := &MockIPerpetualMarketStructureProxy{ctrl: ctrl}
	mock.recorder = &MockIPerpetualMarketStructureProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPerpetualMarketStructureProxy) EXPECT() *MockIPerpetualMarketStructureProxyMockRecorder {
	return m.recorder
}

// FindMarketStructure mocks base method.
func (m *MockIPerpetualMarketStructureProxy) FindMarketStructure(executionContext context.Context, coinSymbol string) (vo.PerpetualMarketStructureVo, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMarketStructure", executionContext, coinSymbol)
	ret0, _ := ret[0].(vo.PerpetualMarketStructureVo)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMarketStructure indicates an expected call of FindMarketStructure.
func (mr *MockIPerpetualMarketStructureProxyMockRecorder) FindMarketStructure(executionContext, coinSymbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMarketStructure", reflect.TypeOf((*MockIPerpetualMarketStructureProxy)(nil).FindMarketStructure), executionContext, coinSymbol)
}
