// Code generated by MockGen. DO NOT EDIT.
// Source: i_coin_insight_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_coin_insight_repository.go -destination=mocks/mock_i_coin_insight_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockICoinInsightRepository is a mock of ICoinInsightRepository interface.
type MockICoinInsightRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICoinInsightRepositoryMockRecorder
	isgomock struct{}
}

// MockICoinInsightRepositoryMockRecorder is the mock recorder for MockICoinInsightRepository.
type MockICoinInsightRepositoryMockRecorder struct {
	mock *MockICoinInsightRepository
}

// NewMockICoinInsightRepository creates a new mock instance.
func NewMockICoinInsightRepository(ctrl *gomock.Controller) *MockICoinInsightRepository {
	mock := &MockICoinInsightRepository{ctrl: ctrl}
	mock.recorder = &MockICoinInsightRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoinInsightRepository) EXPECT() *MockICoinInsightRepositoryMockRecorder {
	return m.recorder
}

// CreateAll mocks base method.
func (m *MockICoinInsightRepository) CreateAll(executionContext context.Context, coinInsights []entities.CoinInsight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAll", executionContext, coinInsights)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAll indicates an expected call of CreateAll.
func (mr *MockICoinInsightRepositoryMockRecorder) CreateAll(executionContext, coinInsights any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAll", reflect.TypeOf((*MockICoinInsightRepository)(nil).CreateAll), executionContext, coinInsights)
}

// FindByPipelineRunID mocks base method.
func (m *MockICoinInsightRepository) FindByPipelineRunID(executionContext context.Context, pipelineRunID uint) ([]entities.CoinInsight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPipelineRunID", executionContext, pipelineRunID)
	ret0, _ := ret[0].([]entities.CoinInsight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPipelineRunID indicates an expected call of FindByPipelineRunID.
func (mr *MockICoinInsightRepositoryMockRecorder) FindByPipelineRunID(executionContext, pipelineRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPipelineRunID", reflect.TypeOf((*MockICoinInsightRepository)(nil).FindByPipelineRunID), executionContext, pipelineRunID)
}
