// Code generated by MockGen. DO NOT EDIT.
// Source: i_information_source_outcome_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_information_source_outcome_repository.go -destination=mocks/mock_i_information_source_outcome_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIInformationSourceOutcomeRepository is a mock of IInformationSourceOutcomeRepository interface.
type MockIInformationSourceOutcomeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInformationSourceOutcomeRepositoryMockRecorder
	isgomock struct{}
}

// MockIInformationSourceOutcomeRepositoryMockRecorder is the mock recorder for MockIInformationSourceOutcomeRepository.
type MockIInformationSourceOutcomeRepositoryMockRecorder struct {
	mock *MockIInformationSourceOutcomeRepository
}

// NewMockIInformationSourceOutcomeRepository creates a new mock instance.
func NewMockIInformationSourceOutcomeRepository(ctrl *gomock.Controller) *MockIInformationSourceOutcomeRepository {
	mock := &MockIInformationSourceOutcomeRepository{ctrl: ctrl}
	mock.recorder = &MockIInformationSourceOutcomeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInformationSourceOutcomeRepository) EXPECT() *MockIInformationSourceOutcomeRepositoryMockRecorder {
	return m.recorder
}

// CreateAll mocks base method.
func (m *MockIInformationSourceOutcomeRepository) CreateAll(executionContext context.Context, informationSourceOutcomes []entities.InformationSourceOutcome) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAll", executionContext, informationSourceOutcomes)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAll indicates an expected call of CreateAll.
func (mr *MockIInformationSourceOutcomeRepositoryMockRecorder) CreateAll(executionContext, informationSourceOutcomes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAll", reflect.TypeOf((*MockIInformationSourceOutcomeRepository)(nil).CreateAll), executionContext, informationSourceOutcomes)
}
