// Code generated by MockGen. DO NOT EDIT.
// Source: i_coin_news_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_coin_news_proxy.go -destination=mocks/mock_i_coin_news_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockICoinNewsProxy is a mock of ICoinNewsProxy interface.
type MockICoinNewsProxy struct {
	ctrl     *gomock.Controller
	recorder *MockICoinNewsProxyMockRecorder
	isgomock struct{}
}

// MockICoinNewsProxyMockRecorder is the mock recorder for MockICoinNewsProxy.
type MockICoinNewsProxyMockRecorder struct {
	mock *MockICoinNewsProxy
}

// NewMockICoinNewsProxy creates a new mock instance.
func NewMockICoinNewsProxy(ctrl *gomock.Controller) *MockICoinNewsProxy {
	mock := &MockICoinNewsProxy{ctrl: ctrl}
	mock.recorder = &MockICoinNewsProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoinNewsProxy) EXPECT() *MockICoinNewsProxyMockRecorder {
	return m.recorder
}

// FindRecentHeadlines mocks base method.
func (m *MockICoinNewsProxy) FindRecentHeadlines(executionContext context.Context, coinSymbol string, since time.Time, limit int) ([]vo.HeadlineVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecentHeadlines", executionContext, coinSymbol, since, limit)
	ret0, _ := ret[0].([]vo.HeadlineVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecentHeadlines indicates an expected call of FindRecentHeadlines.
func (mr *MockICoinNewsProxyMockRecorder) FindRecentHeadlines(executionContext, coinSymbol, since, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecentHeadlines", reflect.TypeOf((*MockICoinNewsProxy)(nil).FindRecentHeadlines), executionContext, coinSymbol, since, limit)
}
