// Code generated by MockGen. DO NOT EDIT.
// Source: i_perpetual_contract_listing_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_perpetual_contract_listing_proxy.go -destination=mocks/mock_i_perpetual_contract_listing_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPerpetualContractListingProxy is a mock of IPerpetualContractListingProxy interface.
type MockIPerpetualContractListingProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIPerpetualContractListingProxyMockRecorder
	isgomock struct{}
}

// MockIPerpetualContractListingProxyMockRecorder is the mock recorder for MockIPerpetualContractListingProxy.
type MockIPerpetualContractListingProxyMockRecorder struct {
	mock *MockIPerpetualContractListingProxy
}

// NewMockIPerpetualContractListingProxy creates a new mock instance.
func NewMockIPerpetualContractListingProxy(ctrl *gomock.Controller) *MockIPerpetualContractListingProxy {
	mock := &MockIPerpetualContractListingProxy{ctrl: ctrl}
	mock.recorder = &MockIPerpetualContractListingProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPerpetualContractListingProxy) EXPECT() *MockIPerpetualContractListingProxyMockRecorder {
	return m.recorder
}

// ExchangeName mocks base method.
func (m *MockIPerpetualContractListingProxy) ExchangeName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeName")
	ret0, _ := ret[0].(string)
	return ret0
}

// ExchangeName indicates an expected call of ExchangeName.
func (mr *MockIPerpetualContractListingProxyMockRecorder) ExchangeName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeName", reflect.TypeOf((*MockIPerpetualContractListingProxy)(nil).ExchangeName))
}

// FindUsdtPerpetualCoinSymbols mocks base method.
func (m *MockIPerpetualContractListingProxy) FindUsdtPerpetualCoinSymbols(executionContext context.Context) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsdtPerpetualCoinSymbols", executionContext)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsdtPerpetualCoinSymbols indicates an expected call of FindUsdtPerpetualCoinSymbols.
func (mr *MockIPerpetualContractListingProxyMockRecorder) FindUsdtPerpetualCoinSymbols(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsdtPerpetualCoinSymbols", reflect.TypeOf((*MockIPerpetualContractListingProxy)(nil).FindUsdtPerpetualCoinSymbols), executionContext)
}
