// Code generated by MockGen. DO NOT EDIT.
// Source: i_information_source_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_information_source_proxy.go -destination=mocks/mock_i_information_source_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIInformationSourceProxy is a mock of IInformationSourceProxy interface.
type MockIInformationSourceProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIInformationSourceProxyMockRecorder
	isgomock struct{}
}

// MockIInformationSourceProxyMockRecorder is the mock recorder for MockIInformationSourceProxy.
type MockIInformationSourceProxyMockRecorder struct {
	mock *MockIInformationSourceProxy
}

// NewMockIInformationSourceProxy creates a new mock instance.
func NewMockIInformationSourceProxy(ctrl *gomock.Controller) *MockIInformationSourceProxy {
	mock := &MockIInformationSourceProxy{ctrl: ctrl}
	mock.recorder = &MockIInformationSourceProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInformationSourceProxy) EXPECT() *MockIInformationSourceProxyMockRecorder {
	return m.recorder
}

// FetchInformationItems mocks base method.
func (m *MockIInformationSourceProxy) FetchInformationItems(executionContext context.Context, itemLimit int) ([]vo.InformationItemVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchInformationItems", executionContext, itemLimit)
	ret0, _ := ret[0].([]vo.InformationItemVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchInformationItems indicates an expected call of FetchInformationItems.
func (mr *MockIInformationSourceProxyMockRecorder) FetchInformationItems(executionContext, itemLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchInformationItems", reflect.TypeOf((*MockIInformationSourceProxy)(nil).FetchInformationItems), executionContext, itemLimit)
}

// SourceName mocks base method.
func (m *MockIInformationSourceProxy) SourceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// SourceName indicates an expected call of SourceName.
func (mr *MockIInformationSourceProxyMockRecorder) SourceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceName", reflect.TypeOf((*MockIInformationSourceProxy)(nil).SourceName))
}
