// Code generated by MockGen. DO NOT EDIT.
// Source: i_coin_market_data_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_coin_market_data_proxy.go -destination=mocks/mock_i_coin_market_data_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockICoinMarketDataProxy is a mock of ICoinMarketDataProxy interface.
type MockICoinMarketDataProxy struct {
	ctrl     *gomock.Controller
	recorder *MockICoinMarketDataProxyMockRecorder
	isgomock struct{}
}

// MockICoinMarketDataProxyMockRecorder is the mock recorder for MockICoinMarketDataProxy.
type MockICoinMarketDataProxyMockRecorder struct {
	mock *MockICoinMarketDataProxy
}

// NewMockICoinMarketDataProxy creates a new mock instance.
func NewMockICoinMarketDataProxy(ctrl *gomock.Controller) *MockICoinMarketDataProxy {
	mock := &MockICoinMarketDataProxy{ctrl: ctrl}
	mock.recorder = &MockICoinMarketDataProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoinMarketDataProxy) EXPECT() *MockICoinMarketDataProxyMockRecorder {
	return m.recorder
}

// FindCoinMarketData mocks base method.
func (m *MockICoinMarketDataProxy) FindCoinMarketData(executionContext context.Context, coinIdentities []vo.CoinIdentityVo) (map[string]vo.CoinMarketDataVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCoinMarketData", executionContext, coinIdentities)
	ret0, _ := ret[0].(map[string]vo.CoinMarketDataVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCoinMarketData indicates an expected call of FindCoinMarketData.
func (mr *MockICoinMarketDataProxyMockRecorder) FindCoinMarketData(executionContext, coinIdentities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCoinMarketData", reflect.TypeOf((*MockICoinMarketDataProxy)(nil).FindCoinMarketData), executionContext, coinIdentities)
}

// SourceName mocks base method.
func (m *MockICoinMarketDataProxy) SourceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// SourceName indicates an expected call of SourceName.
func (mr *MockICoinMarketDataProxyMockRecorder) SourceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceName", reflect.TypeOf((*MockICoinMarketDataProxy)(nil).SourceName))
}
