// Code generated by MockGen. DO NOT EDIT.
// Source: i_coin_insight_analyst_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_coin_insight_analyst_proxy.go -destination=mocks/mock_i_coin_insight_analyst_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockICoinInsightAnalystProxy is a mock of ICoinInsightAnalystProxy interface.
type MockICoinInsightAnalystProxy struct {
	ctrl     *gomock.Controller
	recorder *MockICoinInsightAnalystProxyMockRecorder
	isgomock struct{}
}

// MockICoinInsightAnalystProxyMockRecorder is the mock recorder for MockICoinInsightAnalystProxy.
type MockICoinInsightAnalystProxyMockRecorder struct {
	mock *MockICoinInsightAnalystProxy
}

// NewMockICoinInsightAnalystProxy creates a new mock instance.
func NewMockICoinInsightAnalystProxy(ctrl *gomock.Controller) *MockICoinInsightAnalystProxy {
	mock := &MockICoinInsightAnalystProxy{ctrl: ctrl}
	mock.recorder = &MockICoinInsightAnalystProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoinInsightAnalystProxy) EXPECT() *MockICoinInsightAnalystProxyMockRecorder {
	return m.recorder
}

// AnalyzeCoin mocks base method.
func (m *MockICoinInsightAnalystProxy) AnalyzeCoin(executionContext context.Context, material vo.CoinInsightMaterialVo) (vo.CoinInsightAnswerVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeCoin", executionContext, material)
	ret0, _ := ret[0].(vo.CoinInsightAnswerVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeCoin indicates an expected call of AnalyzeCoin.
func (mr *MockICoinInsightAnalystProxyMockRecorder) AnalyzeCoin(executionContext, material any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeCoin", reflect.TypeOf((*MockICoinInsightAnalystProxy)(nil).AnalyzeCoin), executionContext, material)
}
