// Code generated by MockGen. DO NOT EDIT.
// Source: i_coin_candidate_filter_handler.go
//
// Generated by this command:
//
//	mockgen -source=i_coin_candidate_filter_handler.go -destination=mocks/mock_i_coin_candidate_filter_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockICoinCandidateFilterHandler is a mock of ICoinCandidateFilterHandler interface.
type MockICoinCandidateFilterHandler struct {
	ctrl     *gomock.Controller
	recorder *MockICoinCandidateFilterHandlerMockRecorder
	isgomock struct{}
}

// MockICoinCandidateFilterHandlerMockRecorder is the mock recorder for MockICoinCandidateFilterHandler.
type MockICoinCandidateFilterHandlerMockRecorder struct {
	mock *MockICoinCandidateFilterHandler
}

// NewMockICoinCandidateFilterHandler creates a new mock instance.
func NewMockICoinCandidateFilterHandler(ctrl *gomock.Controller) *MockICoinCandidateFilterHandler {
	mock := &MockICoinCandidateFilterHandler{ctrl: ctrl}
	mock.recorder = &MockICoinCandidateFilterHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoinCandidateFilterHandler) EXPECT() *MockICoinCandidateFilterHandlerMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockICoinCandidateFilterHandler) Evaluate(coinProfile vo.CoinProfileVo) vo.FilterVerdictVo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", coinProfile)
	ret0, _ := ret[0].(vo.FilterVerdictVo)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockICoinCandidateFilterHandlerMockRecorder) Evaluate(coinProfile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockICoinCandidateFilterHandler)(nil).Evaluate), coinProfile)
}

// FilterName mocks base method.
func (m *MockICoinCandidateFilterHandler) FilterName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterName")
	ret0, _ := ret[0].(string)
	return ret0
}

// FilterName indicates an expected call of FilterName.
func (mr *MockICoinCandidateFilterHandlerMockRecorder) FilterName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterName", reflect.TypeOf((*MockICoinCandidateFilterHandler)(nil).FilterName))
}
