// Code generated by MockGen. DO NOT EDIT.
// Source: i_token_unlock_schedule_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_token_unlock_schedule_proxy.go -destination=mocks/mock_i_token_unlock_schedule_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockITokenUnlockScheduleProxy is a mock of ITokenUnlockScheduleProxy interface.
type MockITokenUnlockScheduleProxy struct {
	ctrl     *gomock.Controller
	recorder *MockITokenUnlockScheduleProxyMockRecorder
	isgomock struct{}
}

// MockITokenUnlockScheduleProxyMockRecorder is the mock recorder for MockITokenUnlockScheduleProxy.
type MockITokenUnlockScheduleProxyMockRecorder struct {
	mock *MockITokenUnlockScheduleProxy
}

// NewMockITokenUnlockScheduleProxy creates a new mock instance.
func NewMockITokenUnlockScheduleProxy(ctrl *gomock.Controller) *MockITokenUnlockScheduleProxy {
	mock := &MockITokenUnlockScheduleProxy{ctrl: ctrl}
	mock.recorder = &MockITokenUnlockScheduleProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenUnlockScheduleProxy) EXPECT() *MockITokenUnlockScheduleProxyMockRecorder {
	return m.recorder
}

// FindTokenUnlockEvents mocks base method.
func (m *MockITokenUnlockScheduleProxy) FindTokenUnlockEvents(executionContext context.Context, coinUnlockLookups []vo.CoinUnlockLookupVo) (map[string][]vo.TokenUnlockEventVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTokenUnlockEvents", executionContext, coinUnlockLookups)
	ret0, _ := ret[0].(map[string][]vo.TokenUnlockEventVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTokenUnlockEvents indicates an expected call of FindTokenUnlockEvents.
func (mr *MockITokenUnlockScheduleProxyMockRecorder) FindTokenUnlockEvents(executionContext, coinUnlockLookups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTokenUnlockEvents", reflect.TypeOf((*MockITokenUnlockScheduleProxy)(nil).FindTokenUnlockEvents), executionContext, coinUnlockLookups)
}

// SourceName mocks base method.
func (m *MockITokenUnlockScheduleProxy) SourceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// SourceName indicates an expected call of SourceName.
func (mr *MockITokenUnlockScheduleProxyMockRecorder) SourceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceName", reflect.TypeOf((*MockITokenUnlockScheduleProxy)(nil).SourceName))
}
