// Code generated by MockGen. DO NOT EDIT.
// Source: i_token_security_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_token_security_proxy.go -destination=mocks/mock_i_token_security_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockITokenSecurityProxy is a mock of ITokenSecurityProxy interface.
type MockITokenSecurityProxy struct {
	ctrl     *gomock.Controller
	recorder *MockITokenSecurityProxyMockRecorder
	isgomock struct{}
}

// MockITokenSecurityProxyMockRecorder is the mock recorder for MockITokenSecurityProxy.
type MockITokenSecurityProxyMockRecorder struct {
	mock *MockITokenSecurityProxy
}

// NewMockITokenSecurityProxy creates a new mock instance.
func NewMockITokenSecurityProxy(ctrl *gomock.Controller) *MockITokenSecurityProxy {
	mock := &MockITokenSecurityProxy{ctrl: ctrl}
	mock.recorder = &MockITokenSecurityProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenSecurityProxy) EXPECT() *MockITokenSecurityProxyMockRecorder {
	return m.recorder
}

// FindTokenSecurity mocks base method.
func (m *MockITokenSecurityProxy) FindTokenSecurity(executionContext context.Context, tokenAddress vo.TokenAddressVo) (vo.TokenSecurityVo, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTokenSecurity", executionContext, tokenAddress)
	ret0, _ := ret[0].(vo.TokenSecurityVo)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindTokenSecurity indicates an expected call of FindTokenSecurity.
func (mr *MockITokenSecurityProxyMockRecorder) FindTokenSecurity(executionContext, tokenAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTokenSecurity", reflect.TypeOf((*MockITokenSecurityProxy)(nil).FindTokenSecurity), executionContext, tokenAddress)
}

// SourceName mocks base method.
func (m *MockITokenSecurityProxy) SourceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// SourceName indicates an expected call of SourceName.
func (mr *MockITokenSecurityProxyMockRecorder) SourceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceName", reflect.TypeOf((*MockITokenSecurityProxy)(nil).SourceName))
}

// SupportsChain mocks base method.
func (m *MockITokenSecurityProxy) SupportsChain(chainID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsChain", chainID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsChain indicates an expected call of SupportsChain.
func (mr *MockITokenSecurityProxyMockRecorder) SupportsChain(chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsChain", reflect.TypeOf((*MockITokenSecurityProxy)(nil).SupportsChain), chainID)
}
