// Code generated by MockGen. DO NOT EDIT.
// Source: i_pipeline_run_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_pipeline_run_repository.go -destination=mocks/mock_i_pipeline_run_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-coin-hunter/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIPipelineRunRepository is a mock of IPipelineRunRepository interface.
type MockIPipelineRunRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPipelineRunRepositoryMockRecorder
	isgomock struct{}
}

// MockIPipelineRunRepositoryMockRecorder is the mock recorder for MockIPipelineRunRepository.
type MockIPipelineRunRepositoryMockRecorder struct {
	mock *MockIPipelineRunRepository
}

// NewMockIPipelineRunRepository creates a new mock instance.
func NewMockIPipelineRunRepository(ctrl *gomock.Controller) *MockIPipelineRunRepository {
	mock := &MockIPipelineRunRepository{ctrl: ctrl}
	mock.recorder = &MockIPipelineRunRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPipelineRunRepository) EXPECT() *MockIPipelineRunRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPipelineRunRepository) Create(executionContext context.Context, pipelineRun entities.PipelineRun) (entities.PipelineRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", executionContext, pipelineRun)
	ret0, _ := ret[0].(entities.PipelineRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIPipelineRunRepositoryMockRecorder) Create(executionContext, pipelineRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPipelineRunRepository)(nil).Create), executionContext, pipelineRun)
}

// FindAll mocks base method.
func (m *MockIPipelineRunRepository) FindAll(executionContext context.Context) ([]entities.PipelineRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", executionContext)
	ret0, _ := ret[0].([]entities.PipelineRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIPipelineRunRepositoryMockRecorder) FindAll(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIPipelineRunRepository)(nil).FindAll), executionContext)
}

// FindLatestSucceeded mocks base method.
func (m *MockIPipelineRunRepository) FindLatestSucceeded(executionContext context.Context, step string) (entities.PipelineRun, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestSucceeded", executionContext, step)
	ret0, _ := ret[0].(entities.PipelineRun)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindLatestSucceeded indicates an expected call of FindLatestSucceeded.
func (mr *MockIPipelineRunRepositoryMockRecorder) FindLatestSucceeded(executionContext, step any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestSucceeded", reflect.TypeOf((*MockIPipelineRunRepository)(nil).FindLatestSucceeded), executionContext, step)
}

// FindOne mocks base method.
func (m *MockIPipelineRunRepository) FindOne(executionContext context.Context, pipelineRunID uint) (entities.PipelineRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, pipelineRunID)
	ret0, _ := ret[0].(entities.PipelineRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIPipelineRunRepositoryMockRecorder) FindOne(executionContext, pipelineRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIPipelineRunRepository)(nil).FindOne), executionContext, pipelineRunID)
}

// FindRunning mocks base method.
func (m *MockIPipelineRunRepository) FindRunning(executionContext context.Context) ([]entities.PipelineRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRunning", executionContext)
	ret0, _ := ret[0].([]entities.PipelineRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRunning indicates an expected call of FindRunning.
func (mr *MockIPipelineRunRepositoryMockRecorder) FindRunning(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRunning", reflect.TypeOf((*MockIPipelineRunRepository)(nil).FindRunning), executionContext)
}

// Update mocks base method.
func (m *MockIPipelineRunRepository) Update(executionContext context.Context, pipelineRun entities.PipelineRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", executionContext, pipelineRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIPipelineRunRepositoryMockRecorder) Update(executionContext, pipelineRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIPipelineRunRepository)(nil).Update), executionContext, pipelineRun)
}
